### ISSUE TITLE
[Blocking] SubscriptionsClient.subscribe is not a function!

### ISSUE THREAD

**Issue by Stradivario** [apollographql/GraphiQL-Subscriptions-Fetcher#13]
![screenshot from 2018-09-02 20-45-17](https://user-images.githubusercontent.com/19847933/44959048-57e86700-aef1-11e8-9ad5-7a0e60a1f47e.png)
![screenshot from 2018-09-02 20-45-09](https://user-images.githubusercontent.com/19847933/44959049-5880fd80-aef1-11e8-9019-794f50b9209a.png)
![screenshot from 2018-09-02 20-49-52](https://user-images.githubusercontent.com/19847933/44959071-c88f8380-aef1-11e8-97d2-41d5e1ca4f5f.png)

When i try to subscribe to some topic it says:

```
subscriptionsClient.subscribe is not a function
```

The source is here: 

https://github.com/apollographql/GraphiQL-Subscriptions-Fetcher/blob/master/src/fetcher.ts#L32

Please explain what is going on here and why subscribe is undefined as you can see i have object subscriptionsClient ?

**Comment by akaSybe** [comment]
@Stradivario it's because of breaking changes in subscriptions-transport-ws since 0.9.0

see https://github.com/apollographql/subscriptions-transport-ws/releases/tag/v0.9.0 for more information

you can use version 0.8.3 as a temporary solution

**Comment by Stradivario** [comment]
@akaSybe thank you very much for the explanation! I think i have done the same thing and i forgot to tell it here! Regards!

**Comment by coderdiaz** [comment]
> @Stradivario it's because of breaking changes in subscriptions-transport-ws since 0.9.0
> 
> see https://github.com/apollographql/subscriptions-transport-ws/releases/tag/v0.9.0 for more information
> 
> you can use version 0.8.3 as a temporary solution

Not works for me :(
